version: 0.2

env:
  variables: {}
  parameter-store: {}

phases:
  install:
    commands:
    - echo Entered install phase
    - apt-get update
    - apt-get install hugo

  build:
    commands:
      - echo Entered build phase
      - cd $CODEBUILD_SRC_DIR
      - hugo
      - hugo deploy
  
  post_build:
    commands:
      - echo Build complete
