version: 0.2

env:
  variables: {}
  parameter-store: {}

phases:
  install:
    commands:
    - echo Entered install phase
    - apt-get update
    - apt-get -y install hugo

  build:
    commands:
      - echo Entered build phase
      - cd $CODEBUILD_SRC_DIR
      - hugo
      - hugo deploy
      - aws cloudfront create-invalidation --distribution-id ERIFSQI0Q3XAB --paths "/*"
  
  post_build:
    commands:
      - echo Build complete
